# Generated by Django 4.2.1 on 2023-05-11 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricso', models.CharField()),
                ('responsavel', models.CharField()),
                ('nivel', models.IntegerField()),
                ('prioridade', models.IntegerField(choices=[('NOVA', 'NOVA'), ('EM ANDAMENTO', 'EM ANDAMENTO'), ('PENDENTE', 'PENDENTE'), ('RESOLVIDA', 'RESOLVIDA'), ('CANCELADA', 'CANCELADA')])),
                ('situacao', models.CharField()),
                ('usuaario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
